name: Convert SVG to PNG

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  convert:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        part: [0,1,2,3,4,5,6,7,8,9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Inkscape
        run: sudo apt-get update && sudo apt-get install -y inkscape

      - name: Prepare file list
        run: |
          find Papirus Papirus-Dark Papirus-Light -name "*.svg" | sort > all_files.txt
          split -d -n l/10 all_files.txt files_part_

      - name: Convert SVG to PNG
        run: |
          mkdir -p png

          PART_FILE=$(printf "files_part_%02d" ${{ matrix.part }})

          echo "Using file: $PART_FILE"

          if [ ! -f "$PART_FILE" ]; then
            echo "No file for this part, skipping"
            exit 0
          fi

          while IFS= read -r f; do
            out="png/${f%.svg}.png"
            mkdir -p "$(dirname "$out")"

            inkscape "$f" --export-type=png --export-filename="$out"
          done < "$PART_FILE"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: png-part-${{ matrix.part }}
          path: png

  merge:
    needs: convert
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download all parts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge all PNGs
        run: |
          mkdir -p png
          find artifacts -type f -name "*.png" | while read f; do
            target="png/${f#*/png/}"
            mkdir -p "$(dirname "$target")"
            cp "$f" "$target"
          done

      - name: Commit PNGs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add png
          git commit -m "Auto-generate PNGs" || echo "No changes"

          git push
